name: Vinsona Media Auto Scraper

on:
  schedule:
    # यह रोज़ सुबह भारतीय समयानुसार (IST) 6:30 बजे अपने आप रन होगा
    - cron: '0 1 * * *'
  workflow_dispatch: # इससे आप जब चाहें हाथ से भी रन कर सकते हैं

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/checkout@v4
      with:
        node-version: '20'

    - name: Install Project Dependencies (Firebase & Axios)
      run: |
        npm init -y
        npm install firebase axios

    - name: Run Secret Scraper Script
      run: node scraper.js
